package edu.utm.bd.domain;

public class Producto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.ProPrecioVenta
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private Integer proprecioventa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.ProPrecioCompra
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private Integer propreciocompra;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.ProCantidad
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private Integer procantidad;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.ProNombre
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private String pronombre;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.ProPrecioVenta
	 * @return  the value of producto.ProPrecioVenta
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.IdProduco
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private Integer idproduco;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.Proveedor_id
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	private Integer proveedorId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.IdProduco
	 * @return  the value of producto.IdProduco
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public Integer getIdproduco() {
		return this.idproduco;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.IdProduco
	 * @param idproduco  the value for producto.IdProduco
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setIdproduco(Integer idproduco) {
		this.idproduco = idproduco;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.Proveedor_id
	 * @return  the value of producto.Proveedor_id
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public Integer getProveedorId() {
		return this.proveedorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.Proveedor_id
	 * @param proveedorId  the value for producto.Proveedor_id
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setProveedorId(Integer proveedorId) {
		this.proveedorId = proveedorId;
	}
	
	public Integer getProprecioventa() {
		return this.proprecioventa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.ProPrecioVenta
	 * @param proprecioventa  the value for producto.ProPrecioVenta
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setProprecioventa(Integer proprecioventa) {
		this.proprecioventa = proprecioventa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.ProPrecioCompra
	 * @return  the value of producto.ProPrecioCompra
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public Integer getPropreciocompra() {
		return this.propreciocompra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.ProPrecioCompra
	 * @param propreciocompra  the value for producto.ProPrecioCompra
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setPropreciocompra(Integer propreciocompra) {
		this.propreciocompra = propreciocompra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.ProCantidad
	 * @return  the value of producto.ProCantidad
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public Integer getProcantidad() {
		return this.procantidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.ProCantidad
	 * @param procantidad  the value for producto.ProCantidad
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setProcantidad(Integer procantidad) {
		this.procantidad = procantidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.ProNombre
	 * @return  the value of producto.ProNombre
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public String getPronombre() {
		return this.pronombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.ProNombre
	 * @param pronombre  the value for producto.ProNombre
	 * @mbg.generated  Wed Apr 25 18:55:18 CDT 2018
	 */
	public void setPronombre(String pronombre) {
		this.pronombre = pronombre;
	}
}